### ISSUE TITLE
Current version is limited to 102.0, will stop working when 102.0.1 is released

### ISSUE THREAD

**Issue by jobisoft** [HiraokaHyperTools/InsertSignature#2]
Hi,

your most recent version seems to be compatible with Thunderbird 102, but you are limiting it to 102.0, which means it will no longer work once 102.0.1 is released next week. Could you increase the max value to 102.* ?

**Comment by jobisoft** [comment]
If you encountered issues, which prevent this add-on from running in Thunderbird 102, which I have missed during my tests, I would like to offer my help to hunt them down.

**Comment by kenjiuno** [comment]
Hi @jobisoft 

Thanks you to let me know about incoming TB 102!

Currently I don't develop new features of my TB addons.

I just confirm that functionality is not lost by incoming TB Beta major updates.

My procedures:

1. Launch my installation of TB Beta periodically.
2. Help → About
3. Check for updates. If there is an update, update, restart TB Beta and continue steps. If there is no update, skip following steps.
   ![2022-07-06_22h04_49](https://user-images.githubusercontent.com/5955540/177680997-1eb804eb-742b-42a1-87de-deae7f92ce2f.png)
4. Go to `Manage Version` of ATN.
5. Set maximum version to current major beta so that is matches to TB Beta version.
  ![2022-07-07_12h00_19](https://user-images.githubusercontent.com/5955540/177681462-2eb23a8d-69de-428f-ab94-f19d0036c4d9.png)
6. Back to TB Beta, Tools → Add-ons and themes → Extensions → ⚙ → `Check for Updates`
7. Test and verify add-on functionality. If there is no problem, keep maximum version to TB Beta version. If there is problem, restore maximum version on ATN, and then fix it.

※ I know that this way will not be functional on new submitting of add-on update, because `strict_max_version` will be mandatory now...

**Comment by jobisoft** [comment]
Hi kenjiuno,

thanks for your response and thanks for updating the setting. I would like to point out where the current add-on configuration could cause issues:

On App upgrade (for example, from TB91 to TB102) only the value stored in the XPI is looked at to verify compatibility. You have no value in the XPI so it will always "work" after Thunderbird upgrade even though it might have a major issue. There is no way to disable it in case of an error. It will ship to your users no matter what. Only a fresh add-on installation is affected/limited by the max value defined on ATN.

That is why - whenever possible - I suggest adding the current ESR (102.*) as max version in the XPI (submit a new version with just this change)

You can still update the max value on ATN, but before you do that, the add-on will disable itself on your users installations, protecting them of using it without your verification. So when you verified it for 103 and TB updates to 104, it gets disabled until you have re-verified it for 104.

When the next ESR is being released (probably 114), I suggest uploading a new version with an updated max value in the XPI. The reason here is that offline installs cannot check ATN, which means your add-on will fail to offline-install in 114, if the XPI is limiting it to 102.*

So my best practice suggestion is:
- verify with each new ESR and upload a new version with a proper strict_max-version setting
- verify with each new BETA and change the value on ATN

Have a great day and thanks for your time!

Edit: All this is of course only valid for Experiments. Pure WebExtension do not need a max version setting at all.

**Comment by kenjiuno** [comment]
Thanks again,
The max version is set to current ESR (102.*) on InsertSignature `0.3.0`.
I'll keep up watching incoming TB Beta versions.
